logger:
  level: info

db:
  mysql:
    # Use secrets.yaml to define database and other credentials
    # host:
    # port:
    # database:
    # user:
    # password:
    poolLimit: 30

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
